#!/bin/bash

# Dotfiles init
export DOTFILES=$HOME/.dotfiles

# Configs
ln -s $DOTFILES/bash_profile         $HOME/.bash_profile
ln -s $DOTFILES/vimrc           $HOME/.vimrc
ln -s $DOTFILES/ackrc           $HOME/.ackrc
ln -s $DOTFILES/gitignore       $HOME/.gitignore
ln -s $DOTFILES/tmux            $HOME/.tmux.conf
ln -s $DOTFILES/ctags            $HOME/.ctags
